version: "3.7"

services:
  wdresolve:
    image: ghcr.io/fau-cdi/wdresolve:latest
    restart: always
    volumes:
      - "${PREFIX_FILE}:/prefixes.cfg:ro"
    environment:
      # port and hostname for this image to use
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /go/
      
      # optional letsencrypt email
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

      # default and legacy domain
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      LEGACY_DOMAIN: ${LEGACY_DOMAIN}

      # the prefix file
      PREFIX_FILE: /prefixes.cfg

networks:
  default:
    external:
      name: distillery
