version: "2"
issues:
  max-issues-per-linter: 0
linters:
  default: standard
  settings:
#    nolintlint:
#      allow-unused: false
#      require-explanation: true
#      require-specific: true
    wrapcheck:
      ignore-package-globs:
        - go.tkw01536.de/pkglib/errorsx
        - go.tkw01536.de/pkglib/exit
  disable:
    - bodyclose
  enable:
    - bidichk
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - govet
    - iface
    - intrange
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - staticcheck
    - tagalign
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck