version: "3.7"

services:
    ssh:
        image: tkw01536/proxyssh
        command: -hostkey /keys/hostkey -shell /user_shell.sh -keylabel eu.wiss-ki.barrel.authfile -userlabel eu.wiss-ki.barrel.slug -L triplestore:7200
        ports:
            - "2222:2222"
        volumes:
            - './data/keys:/keys'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        restart: always

networks:
    default:
        external:
          name: distillery
