// Code generated by build.mjs; DO NOT EDIT.

package assets

import _ "embed"

//go:embed "assets_disclaimer.txt"
var Disclaimer string

// Public holds the path to the public route 
const Public = "/⛰/"

// AssetsDefault contains assets for the 'Default' entrypoint.
var AssetsDefault = Assets{
	Scripts: `<script type=module src=/⛰/Default.6170ef04.js></script><script type=module src=/⛰/Default.68829c56.js></script>`,
	Styles:  `<link rel=stylesheet href=/⛰/Default.588cd9f6.css><link rel=stylesheet href=/⛰/Default.3aa0e51f.css>`,	
}

// AssetsUser contains assets for the 'User' entrypoint.
var AssetsUser = Assets{
	Scripts: `<script type=module src=/⛰/Default.6170ef04.js></script><script type=module src=/⛰/User.ae7af732.js></script>`,
	Styles:  `<link rel=stylesheet href=/⛰/Default.588cd9f6.css><link rel=stylesheet href=/⛰/User.540c0bee.css><link rel=stylesheet href=/⛰/User.1664d889.css>`,	
}

// AssetsAdmin contains assets for the 'Admin' entrypoint.
var AssetsAdmin = Assets{
	Scripts: `<script type=module src=/⛰/User.ae7af732.js></script><script type=module src=/⛰/Default.6170ef04.js></script><script type=module src=/⛰/Admin.3b88bd90.js></script>`,
	Styles:  `<link rel=stylesheet href=/⛰/Default.588cd9f6.css><link rel=stylesheet href=/⛰/User.540c0bee.css><link rel=stylesheet href=/⛰/User.1664d889.css><link rel=stylesheet href=/⛰/Admin.7d5bb717.css><link rel=stylesheet href=/⛰/Admin.b6d8ffd6.css>`,	
}

// AssetsAdminProvision contains assets for the 'AdminProvision' entrypoint.
var AssetsAdminProvision = Assets{
	Scripts: `<script type=module src=/⛰/User.ae7af732.js></script><script type=module src=/⛰/Admin.3b88bd90.js></script><script type=module src=/⛰/Default.6170ef04.js></script><script type=module src=/⛰/AdminProvision.980fdbd4.js></script>`,
	Styles:  `<link rel=stylesheet href=/⛰/Default.588cd9f6.css><link rel=stylesheet href=/⛰/User.540c0bee.css><link rel=stylesheet href=/⛰/User.1664d889.css><link rel=stylesheet href=/⛰/Admin.7d5bb717.css><link rel=stylesheet href=/⛰/Admin.b6d8ffd6.css><link rel=stylesheet href=/⛰/AdminProvision.8569d237.css>`,	
}

// AssetsAdminRebuild contains assets for the 'AdminRebuild' entrypoint.
var AssetsAdminRebuild = Assets{
	Scripts: `<script type=module src=/⛰/User.ae7af732.js></script><script type=module src=/⛰/Admin.3b88bd90.js></script><script type=module src=/⛰/Default.6170ef04.js></script><script type=module src=/⛰/AdminRebuild.c84b59f3.js></script>`,
	Styles:  `<link rel=stylesheet href=/⛰/Default.588cd9f6.css><link rel=stylesheet href=/⛰/User.540c0bee.css><link rel=stylesheet href=/⛰/User.1664d889.css><link rel=stylesheet href=/⛰/Admin.7d5bb717.css><link rel=stylesheet href=/⛰/Admin.b6d8ffd6.css><link rel=stylesheet href=/⛰/AdminRebuild.e554824e.css>`,	
}
