version: "3.7"

services:
  dis:
    build: .
    restart: always
    environment:
      # port and hostname for this image to use
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8888

      CONFIG_PATH: ${CONFIG_PATH}
      
      # optional letsencrypt email
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    volumes:
      # TODO: Mount docker socket properly!
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONFIG_PATH}:${CONFIG_PATH}:ro"
      - "${DEPLOY_ROOT}:${DEPLOY_ROOT}:ro"
      - "${GLOBAL_AUTHORIZED_KEYS_FILE}:${GLOBAL_AUTHORIZED_KEYS_FILE}:ro"
      - "${SELF_OVERRIDES_FILE}:${SELF_OVERRIDES_FILE}:ro"

networks:
  default:
    name: distillery
    external: true
