<?php

// Use this file to manually tweak settings of this instance in an update-agnostic way.
// This file will not be updated by future distillery updates.
//
// The settings.php file contains settings in the following order:
//
// - settings generated by the drupal installer
// - global distillery settings files
// - distillery generated configuration files
// - this file
//
// Because of caching, changes may require an instance restart to take effect.

// // e.g. to turn on verbose logging, uncomment the following line:
// $config["system.logging"]["error_level"] = "verbose";
