version: "3.7"

services:
    triplestore:
        build: .
        ports:
            - "127.0.0.1:7200:7200"
        volumes:
            - './data/data:/opt/graphdb/data'
            - './data/work:/opt/graphdb/work'
            - './data/logs:/opt/graphdb/logs'
        # Use 1GB of heap space
        environment:
            GDB_MAX_MEM: 4G
            GDB_MIN_MEM: 1G

        restart: always

networks:
    default:
        external:
          name: distillery
