version: "3.7"

services:
  tr:
    image: ghcr.io/tkw1536/tr:latest
    restart: always
    volumes:
      - "${OVERRIDES_FILE}:/overrides.json:ro"
    environment:
      # port and hostname for this image to use
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      
      # optional letsencrypt email
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

      # the overrides file
      OVERRIDES: /overrides.json

      # where to redirect to
      TARGET: ${TARGET}

networks:
  default:
    external:
      name: distillery
