services:
  ssh:
    read_only: true
    build: .
    restart: always
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONFIG_PATH}:${CONFIG_PATH}:ro"
      - "${DEPLOY_ROOT}:${DEPLOY_ROOT}:rw"
      - "${SELF_OVERRIDES_FILE}:${SELF_OVERRIDES_FILE}:ro"
      - "${SELF_RESOLVER_BLOCK_FILE}:${SELF_RESOLVER_BLOCK_FILE}:ro"
      - "./data/:/data/"

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
