version: "3.7"

services:
    ssh:
        image: ghcr.io/tkw1536/dockersshd:latest
        command: -hostkey /keys/hostkey -shell /user_shell.sh -keylabel eu.wiss-ki.barrel.authfile -userlabel eu.wiss-ki.barrel.slug -L triplestore:7200 -L phpmyadmin:80 -L sql:3306
        ports:
            - "2223:2222"
        volumes:
            - './data/keys:/keys'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        labels:
            - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"
        restart: always

networks:
    default:
        name: ${DOCKER_NETWORK_NAME}
        external: true

