services:
  barrel:
    build:
      context: barrel
      args:
        BARREL_BASE_IMAGE: ${BARREL_BASE_IMAGE}
        PHP_CONFIG_MODE: ${PHP_CONFIG_MODE}
        CONTENT_SECURITY_POLICY: ${CONTENT_SECURITY_POLICY}
        IIP_SERVER_ENABLED: ${IIP_SERVER_ENABLED}

    logging:
      driver: none
    
    restart: always
    hostname: ${WISSKI_HOSTNAME}

    # label it with the current slug
    labels:
      - "traefik.enable=True"
      - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"

      - "traefik.http.routers.wisski_${SLUG}.rule=${HOST_RULE}"
      - "traefik.http.routers.wisski_${SLUG}.tls=${HTTPS_ENABLED}"
      - "traefik.http.routers.wisski_${SLUG}.tls.certresolver=distillery"
      - "traefik.http.services.wisski_${SLUG}.loadbalancer.server.port=8080"

      # more middlewares and labels will be added dynamically.

    
    # volumes that are mounted
    volumes:
      - ${RUNTIME_DIR}:/runtime:ro
      - ${DATA_PATH}/.composer:/var/www/.composer:rw
      - ${DATA_PATH}/data:/var/www/data:rw
      - ${DATA_PATH}/home:/var/www:rw
      - ${DATA_PATH}/hostkeys:/ssh/hostkeys:rw
      - ${LOCAL_SETTINGS_PATH}:${LOCAL_SETTINGS_MOUNT}:ro
      - ${PHP_INI_PATH}:${PHP_INI_MOUNT}:ro
    
    networks:
      - local
      - global
 
    depends_on:
      - dedicatedsql

  # Dedicated SQL server.
  # This service is removed when not in use. 
  dedicatedsql:
    image: mariadb:11.8
    volumes:
        - "${DATA_PATH}/sql:/var/lib/mysql"
        - "${DATA_PATH}/sql_config/conf.d/:/etc/mysql/conf.d:ro"
        - "${DATA_PATH}/sql_imports/:/imports/"
    environment:
        # This combination of environment variables will configure a passwordless root user
        # that can only connect to the container from 'localhost'.
        # This means we can only connect using 'docker-compose exec sql mysql -C '...' '. 
        - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
        - "MYSQL_ROOT_HOST=localhost"
    networks:
      - local

networks:
  global:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  local:
