version: "3.7"

services:
  barrel:
    build: .
    restart: always
    hostname: ${WISSKI_HOSTNAME}

    # label it with the current slug
    labels:
      - "traefik.enable=True"
      - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"

      - "traefik.http.routers.wisski_${SLUG}.rule=${HOST_RULE}"
      - "traefik.http.routers.wisski_${SLUG}.tls=${HTTPS_ENABLED}"
      - "traefik.http.routers.wisski_${SLUG}.tls.certresolver=distillery"
      - "traefik.http.services.wisski_${SLUG}.loadbalancer.server.port=8080"
    
    # volumes that are mounted
    volumes:
      - ${DATA_PATH}/.composer:/var/www/.composer
      - ${DATA_PATH}/data:/var/www/data
      - ${DATA_PATH}/home:/var/www/
      - ${DATA_PATH}/hostkeys:/ssh/hostkeys:rw
      - ${RUNTIME_DIR}:/runtime:ro

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
