version: "3.7"

services:
  barrel:
    build: .
    restart: always
    hostname: ${VIRTUAL_HOST}.wisski

    # label it with the current slug
    labels:
      - "eu.wiss-ki.barrel.slug=${SLUG}"
      - "eu.wiss-ki.barrel.authfile=/var/www/.ssh/authorized_keys,/var/www/.ssh/global_authorized_keys"

      - "traefik.enable=True"
      - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"

      - "traefik.http.routers.wisski_${SLUG}.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.wisski_${SLUG}.tls=${HTTPS_ENABLED}"
      - "traefik.http.routers.wisski_${SLUG}.tls.certresolver=distillery"
      - "traefik.http.services.wisski_${SLUG}.loadbalancer.server.port=8080"
    
    # volumes that are mounted
    volumes:
      - ${GLOBAL_AUTHORIZED_KEYS_FILE}:/var/www/.ssh/global_authorized_keys:ro
      - ${DATA_PATH}/.composer:/var/www/.composer
      - ${DATA_PATH}/data:/var/www/data
      - ${DATA_PATH}/hostkeys:/ssh/hostkeys:rw
      - ${DATA_PATH}/authorized_keys:/var/www/.ssh/authorized_keys
      - ${RUNTIME_DIR}:/runtime:ro

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
