version: "3.7"

services:
  barrel:
    build: .
    restart: always
    hostname: ${VIRTUAL_HOST}.wisski
    environment:
      # port and hostname for this image to use
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      
      # optional letsencrypt email
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    
    # label it with the current slug
    labels:
      eu.wiss-ki.barrel.slug: ${SLUG}
      eu.wiss-ki.barrel.authfile: /var/www/.ssh/authorized_keys,/var/www/.ssh/global_authorized_keys
    
    # volumes that are mounted
    volumes:
      - ${GLOBAL_AUTHORIZED_KEYS_FILE}:/var/www/.ssh/global_authorized_keys:ro
      - ${REAL_PATH}/.composer:/var/www/.composer
      - ${REAL_PATH}/data:/var/www/data
      - ${REAL_PATH}/authorized_keys:/var/www/.ssh/authorized_keys
      - ${DISTILLERY_DIR}/utils:/utils:ro

networks:
  default:
    external:
      name: distillery
