version: "3.7"

services:
  barrel:
    build: .
    restart: always
    environment:
      # port and hostname for this image to use
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      
      # optional letsencrypt email
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    
    # label it with the current slug
    labels:
      eu.wiss-ki.barrel.slug: ${SLUG}
    
    # the volumes to 
    volumes:
      - ${REAL_PATH}/.composer:/var/www/.composer
      - ${REAL_PATH}/data:/var/www/data

networks:
  default:
    external:
      name: distillery
