listen:
    # A list of ports the distillery should accept traffic on.
    # Each of these ports accepts http, https and ssh traffic via a multiplexer.
    ports: null

    # The ssh port that is shown to the user in various interfaces.
    # This port is automatically included in the ports to listen to.
    ssh: null

paths:
    # A WissKI Distillery needs to store a lot of data on disk.
    # This setting defines a root folder all of these will be placed in.
    # On top of this all real-system space will be created under this directory
    root: null

    # Individual paths on the root domain can be overwritten.
    # This can be achieved by adding URLs (without trailing '/'s) into a JSON file.
    # This setting defines the path to that file.
    overrides: null

    # You can block specific prefixes within Triplestore from showing up in the global resolver.
    # Do this by adding one prefix per line in this file.
    # Lines starting with '#' and blank lines are ignored.
    # This setting defines the path to that file.
    blocks: null

http:
  # Each created Drupal Instance corresponds to a single domain name. 
  # These domain names should either be a complete domain name or a sub-domain of a default domain. 
  # This setting configures the default domain-name to create subdomains of. 
  domain: null

  # By default, only the 'domain' domain above is caught.
  # To catch additional domains, add them here
  domains: []

  # The system can support setting up certificate(s) automatically. 
  # It can be enabled by setting an email for certbot certificates. 
  # This email address can be configured here. 
  certbot_email: null

# By default, the default domain redirects to the distillery repository. 
# If you want to change this, set an alternate domain name here. 
theme:
  home: null

docker:
  # The distillery uses several global docker networks.
  # This determines the prefix to use for those networks.
  network: null

# Configuration of the sql backend
sql:
  # username and password for the sql administrative user.
  # this user is automatically created.
  username: null
  password: null

  # prefixes for the data and users to be created and managed
  # one of these is created per WissKI instance.
  user_prefix: null
  data_prefix: null

  # database used for internal configuration
  database: null

# configuration of the triplestore backend
triplestore:
  # admin user and password of the graphdb interface
  # this will be created automatically.
  username: null
  password: null

  # prefixes for the users and repositories to be created
  user_prefix: null
  data_prefix: null

# The maximum agefor backups to be kept. 
# Backups older than this will be removed when a new backup is made.
# The default here is 720hours (== 30 days)
age: null

# Various components use password-based-authentication. 
# These passwords are generated automatically. 
# This variable can be used to determine their length. 
password_length: null

# The secret for sessions (for login etc)
session_secret: null

# the interval to run cron in
cron_interval: null