package field

// Autocomplete represents different autocomplete options
type Autocomplete string

const (
	Off                 Autocomplete = "off"
	On                  Autocomplete = "on"
	Name                Autocomplete = "name"
	HonorificPrefix     Autocomplete = "honorific-prefix"
	GivenName           Autocomplete = "given-name"
	AdditionalName      Autocomplete = "additional-name"
	FamilyName          Autocomplete = "family-name"
	HonorificSuffix     Autocomplete = "honorific-suffix"
	Nickname            Autocomplete = "nickname"
	Email_              Autocomplete = "email"
	Username            Autocomplete = "username"
	NewPassword         Autocomplete = "new-password"
	CurrentPassword     Autocomplete = "current-password"
	OneTimeCode         Autocomplete = "one-time-code"
	OrganizationTitle   Autocomplete = "organization-title"
	Organization        Autocomplete = "organization"
	AddressLine1        Autocomplete = "address-line1"
	AddressLine2        Autocomplete = "address-line2"
	AddressLine3        Autocomplete = "address-line3"
	StreetAddress       Autocomplete = "street-address"
	AddressLevel4       Autocomplete = "address-level4"
	AddressLevel3       Autocomplete = "address-level3"
	AddressLevel2       Autocomplete = "address-level2"
	AddressLevel1       Autocomplete = "address-level1"
	Country             Autocomplete = "country"
	CountryName         Autocomplete = "country-name"
	PostalCode          Autocomplete = "postal-code"
	CcName              Autocomplete = "cc-name"
	CcGivenName         Autocomplete = "cc-given-name"
	CcAdditionalName    Autocomplete = "cc-additional-name"
	CcFamilyName        Autocomplete = "cc-family-name"
	CcNumber            Autocomplete = "cc-number"
	CcExp               Autocomplete = "cc-exp"
	CcExpMonth          Autocomplete = "cc-exp-month"
	CcExpYear           Autocomplete = "cc-exp-year"
	CcCsc               Autocomplete = "cc-csc"
	CcType              Autocomplete = "cc-type"
	TransactionCurrency Autocomplete = "transaction-currency"
	TransactionAmount   Autocomplete = "transaction-amount"
	Language            Autocomplete = "language"
	Bday                Autocomplete = "bday"
	BdayDay             Autocomplete = "bday-day"
	BdayMonth           Autocomplete = "bday-month"
	BdayYear            Autocomplete = "bday-year"
	Sex                 Autocomplete = "sex"
	Tel_                Autocomplete = "tel"
	TelCountryCode      Autocomplete = "tel-country-code"
	TelNational         Autocomplete = "tel-national"
	TelAreaCode         Autocomplete = "tel-area-code"
	TelLocal            Autocomplete = "tel-local"
	TelLocalPrefix      Autocomplete = "tel-local-prefix"
	TelLocalSuffix      Autocomplete = "tel-local-suffix"
	TelExtension        Autocomplete = "tel-extension"
	Impp                Autocomplete = "impp"
	Url_                Autocomplete = "url"
	Photo               Autocomplete = "photo"
)
