version: "3.7"

services:
    triplestore:
        build: .
        ports:
            - "127.0.0.1:7200:7200"
        volumes:
            - './data/data:/opt/graphdb/data'
            - './data/work:/opt/graphdb/work'
            - './data/logs:/opt/graphdb/logs'
            - './data/import:/opt/graphdb/import'
        command: "\"-Dgraphdb.home=/opt/graphdb -Dgraphdb.workbench.importDirectory=/opt/graphdb/import -Ddefault.min.distinct.threshold=16M\""
        environment:
            GDB_HEAP_SIZE: 16G
        labels:
            - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"

        restart: always

networks:
    default:
        name: ${DOCKER_NETWORK_NAME}
        external: true