services:
  static:
    image: tkw01536/gostatic
    restart: always
    ports:
      - 8043
    
    labels:
      - "traefik.enable=True"
      - "eu.wiss-ki.barrel.distillery=${DOCKER_NETWORK_NAME}"

      - "traefik.http.routers.reserve_${SLUG}.rule=${HOST_RULE}"
      - "traefik.http.routers.reserve_${SLUG}.tls=${HTTPS_ENABLED}"
      - "traefik.http.routers.reserve_${SLUG}.tls.certresolver=distillery"
      - "traefik.http.services.reserve_${SLUG}.loadbalancer.server.port=8043"

    
    # volumes that are mounted
    volumes:
      - ./index.html:/srv/http/index.html:ro

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
